In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/Crop_Yield_Prediction.csv')
data.head()

Nitrogen  Phosphorus  Potassium  Temperature   Humidity  pH_Value  \
0        90          42         43    20.879744  82.002744  6.502985   
1        85          58         41    21.770462  80.319644  7.038096   
2        60          55         44    23.004459  82.320763  7.840207   
3        74          35         40    26.491096  80.158363  6.980401   
4        78          42         42    20.130175  81.604873  7.628473   

     Rainfall  Crop   Yield  
0  202.935536  Rice    7000  
1  226.655537  Rice    5000  
2  263.964248  Rice    7000  
3  242.864034  Rice    7000  
4  262.717340  Rice  120000

In [ ]:
data.isnull().sum()

Nitrogen       0
Phosphorus     0
Potassium      0
Temperature    0
Humidity       0
pH_Value       0
Rainfall       0
Crop           0
Yield          0
dtype: int64

In [ ]:
data.shape

(2200, 9)

In [ ]:
pip install pycaret

In [ ]:
from pycaret.classification import *

In [ ]:
model = setup(data = data, target = 'Crop' , categorical_features = ['Nitrogen','Phosphorus','Potassium','Temperature','Humidity','pH_Value','Rainfall'])

In [ ]:
best_model = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [ ]:
x=data.iloc[:,:-2]
y=data.iloc[:,-2]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))

[[22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  1  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  2  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1

In [ ]:
print(accuracy_score(y_test,y_pred))

0.9704545454545455


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       Apple       1.00      1.00      1.00        22
      Banana       1.00      1.00      1.00        18
   Blackgram       1.00      1.00      1.00        22
    ChickPea       1.00      1.00      1.00        15
     Coconut       1.00      1.00      1.00        18
      Coffee       0.94      1.00      0.97        17
      Cotton       0.91      0.95      0.93        22
      Grapes       1.00      1.00      1.00        29
        Jute       0.92      0.88      0.90        25
 KidneyBeans       1.00      1.00      1.00        20
      Lentil       0.90      1.00      0.95        18
       Maize       0.94      0.85      0.89        20
       Mango       1.00      1.00      1.00        17
   MothBeans       0.96      0.96      0.96        24
    MungBean       1.00      0.96      0.98        24
   Muskmelon       1.00      1.00      1.00        26
      Orange       1.00      1.00      1.00        15
      Papaya       0.92    

# Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=None,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
y_pred1 = rfc.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,y_pred1))

[[22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

In [ ]:
print(accuracy_score(y_test,y_pred1))

0.9977272727272727


In [ ]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

       Apple       1.00      1.00      1.00        22
      Banana       1.00      1.00      1.00        18
   Blackgram       1.00      1.00      1.00        22
    ChickPea       1.00      1.00      1.00        15
     Coconut       1.00      1.00      1.00        18
      Coffee       1.00      1.00      1.00        17
      Cotton       1.00      1.00      1.00        22
      Grapes       1.00      1.00      1.00        29
        Jute       0.96      1.00      0.98        25
 KidneyBeans       1.00      1.00      1.00        20
      Lentil       1.00      1.00      1.00        18
       Maize       1.00      1.00      1.00        20
       Mango       1.00      1.00      1.00        17
   MothBeans       1.00      1.00      1.00        24
    MungBean       1.00      1.00      1.00        24
   Muskmelon       1.00      1.00      1.00        26
      Orange       1.00      1.00      1.00        15
      Papaya       1.00    

In [ ]:
from sklearn.linear_model import RidgeClassifier

In [ ]:
ridge_clf = RidgeClassifier()

In [ ]:
ridge_clf.fit(x_train, y_train)

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=None, solver='auto',
                tol=0.0001)

In [ ]:
y_pred_ridge = ridge_clf.predict(x_test)

In [ ]:
print(confusion_matrix(y_test, y_pred_ridge))

[[22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  1  8  0  0  1  0  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  6  0  0  0  0  0  2  2  0 10  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  8

In [ ]:
print(accuracy_score(y_test, y_pred_ridge))

0.6613636363636364


In [ ]:
print(classification_report(y_test, y_pred_ridge))

              precision    recall  f1-score   support

       Apple       0.49      1.00      0.66        22
      Banana       0.69      1.00      0.82        18
   Blackgram       0.79      0.68      0.73        22
    ChickPea       0.68      1.00      0.81        15
     Coconut       0.90      1.00      0.95        18
      Coffee       0.94      1.00      0.97        17
      Cotton       0.72      0.95      0.82        22
      Grapes       1.00      0.21      0.34        29
        Jute       0.00      0.00      0.00        25
 KidneyBeans       0.71      1.00      0.83        20
      Lentil       0.50      1.00      0.67        18
       Maize       1.00      0.20      0.33        20
       Mango       0.55      0.94      0.70        17
   MothBeans       1.00      0.04      0.08        24
    MungBean       1.00      0.67      0.80        24
   Muskmelon       0.79      1.00      0.88        26
      Orange       0.44      0.73      0.55        15
      Papaya       0.54    

In [ ]:
from sklearn.ensemble import VotingClassifier

In [ ]:
ensemble_model = VotingClassifier(estimators=[('lr', model), ('rf', rfc), ('rc', ridge_clf)], voting='hard')

In [ ]:
ensemble_model.fit(x_train, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     ccp_alpha=0.0,
                                                     class_weight=None,
                                                     cr...
                                                     min_weight_fraction_leaf=0.0,
                                                     monotonic_cst=None,
                                                     n_estimators=100,
                                                     n_jobs=None,
                                                     oob_score=False,
                                                     random_state=None,
                                                     verbose=0,
                                                     warm_start=False)),
                             ('rc',
                              RidgeClassifier(alpha=1.0, class_weight=None,
                                              copy_X=True, fit_intercept=True,
                                              max_iter=None, positive=False,
                                              random_state=None, solver='auto',
                                              tol=0.0001))],
                 flatten_transform=True, n_jobs=None, verbose=False,
                 voting='hard', weights=None)

In [ ]:
y_pred_ensemble = ensemble_model.predict(x_test)

In [ ]:
print(confusion_matrix(y_test, y_pred_ensemble))

[[22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  1  0  0  0  0 18  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1

In [ ]:
print(accuracy_score(y_test, y_pred_ensemble))

0.9818181818181818


In [ ]:
print(classification_report(y_test, y_pred_ensemble))

              precision    recall  f1-score   support

       Apple       1.00      1.00      1.00        22
      Banana       0.95      1.00      0.97        18
   Blackgram       1.00      1.00      1.00        22
    ChickPea       1.00      1.00      1.00        15
     Coconut       1.00      1.00      1.00        18
      Coffee       1.00      1.00      1.00        17
      Cotton       0.96      1.00      0.98        22
      Grapes       1.00      1.00      1.00        29
        Jute       0.96      0.92      0.94        25
 KidneyBeans       1.00      1.00      1.00        20
      Lentil       0.90      1.00      0.95        18
       Maize       1.00      0.90      0.95        20
       Mango       1.00      1.00      1.00        17
   MothBeans       1.00      0.96      0.98        24
    MungBean       1.00      0.96      0.98        24
   Muskmelon       1.00      1.00      1.00        26
      Orange       1.00      1.00      1.00        15
      Papaya       1.00    

In [ ]:
import pickle

In [ ]:
with open('RecommendationModel.pkl','wb') as file:
  pickle.dump(ensemble_model, file)

In [ ]:
code = """import streamlit as st

with open('RecommendationModel.pkl', 'rb') as file:
    model = pickle.load(file)

st.title("Crop Yield Prediction App")

st.sidebar.header("Input Features")
nitrogen = st.sidebar.number_input("Nitrogen", min_value=0)
phosphorus = st.sidebar.number_input("Phosphorus", min_value=0)
potassium = st.sidebar.number_input("Potassium", min_value=0)
temperature = st.sidebar.number_input("Temperature", min_value=0)
humidity = st.sidebar.number_input("Humidity", min_value=0)
ph_value = st.sidebar.number_input("pH Value", min_value=0)
rainfall = st.sidebar.number_input("Rainfall", min_value=0)

if st.button("Predict Crop"):
    input_data = pd.DataFrame([[nitrogen, phosphorus, potassium, temperature, humidity, ph_value, rainfall]],
                              columns=['Nitrogen', 'Phosphorus', 'Potassium', 'Temperature', 'Humidity', 'pH_Value', 'Rainfall'])

    prediction = model.predict(input_data)[0]

    st.subheader("Predicted Crop:")
    st.write(prediction)"""

with open('Recommandation_Model.py', 'w') as file:
    file.write(code)

In [ ]:
!streamlit run Recommandation_Model.py




  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.69.56.235:8501

  Stopping...
  Stopping...
